codecov:
  branch: master
coverage:
  range: 50...80
  round: down
  precision: 2
  parsers:
    javascript:
      enable_partials: yes
  ignore:
    - "**/*.yml"
    - "**/*.json"
    - "**/*.md"
    - "**/*.lock"
    - ".eslint*"
    - ".gitignore"
    - "jest.config.js"
    - "util/values.ts"